config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :features do
    resources :comments
  end
  root "features#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :feature
  belongs_to :user
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :features
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def create
    @feature = Feature.find(params[:feature_id])
    @comment = @feature.comments.create(params[:comment].permit(:name, :body))
    @comment.user = current_user
    @comment.save
    
    redirect_to feature_path(@feature)
  end

  def destroy
    @feature = Feature.find(params[:feature_id])
    @comment = @feature.comments.find(params[:id])
    @comment.destroy

    redirect_to feature_path(@feature)
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @features = Feature.all.order('created_at DESC')
  end

  def new
    @feature = current_user.features.build
  end

  def create
    @feature = current_user.features.build(feature_params)

    if @feature.save
      redirect_to @feature
    else
      render 'new'
    end
  end

  def show
    @feature = Feature.find(params[:id])
  end

  def edit
    @feature = Feature.find(params[:id])
  end

  def update
    @feature = Feature.find(params[:id])

    if @feature.update(params[:feature].permit(:title, :body))
      redirect_to @feature
    else
      render 'edit'
    end
  end

  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy

    redirect_to root_path
  end

  private
    def feature_params
      params.require(:feature).permit(:title, :body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.name %></p>
<%= comment.user.email %>

<date><%= time_ago_in_words(comment.created_at) %></date>

<p><%= comment.body %></p>

<% if user_signed_in? %>
  <p><%= link_to 'Delete', [comment.feature, comment], method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@feature, @feature.comments.build]) do |f| %>
  
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %><br>
<% end %>

app/views/features/_forms.html.erb
<%= form_for @feature do |f| %>
  <% if @feature.errors.any? %>
    <%= pluralize(@feature.errors.count, "error") %> prevented this post from saving.
    <ul>
      <% @feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :title %>
  <% if @feature.errors[:title].any? %>
    <ul>
    <% @feature.errors[:title].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %><br>
<% end %>

app/views/features/edit.html.erb
<h1>Edit Feature</h1>

<%= render 'forms' %>

app/views/features/index.html.erb
<% @features.each do |feature| %>
  <h2><%= link_to feature.title, feature %></h2>
  <date><%= feature.created_at.strftime("%B, %d, %Y") %></date>
<% end %>

app/views/features/new.html.erb
<h1>New Feature</h1>

<%= form_for :feature, url: features_path do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %><br>
<% end %>

app/views/features/show.html.erb
<h1><%= @feature.title %></h1>

<date><%= time_ago_in_words(@feature.created_at) %></date>
<p><%= @feature.user.email %></p>

<p><%= @feature.body %></p>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_feature_path(@feature) %>
  <%= link_to 'Delete', feature_path(@feature), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<hr>

<p><%= @feature.comments.count %> Comments</p>
<%= render @feature.comments %>
<%= render "comments/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeatureList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <%= link_to "New Feature", new_feature_path %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    <p>Welcome back <%= current_user.first_name %> <%= current_user.last_name %></p>
    <%= link_to('Your Account', edit_user_registration_path) %>
  <% end %>
  <% if !user_signed_in? %>
    <%= link_to('Login', new_user_session_path) %>
    <%= link_to('Create Account', new_user_registration_path) %>
  <% end %>
<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert") %>
<% end %>
<% if current_page?(root_path) %>
  <h1>Feature List</h1>
  <% else %>
  <%= link_to 'See All Features', root_path %>
<% end %>
<%= yield %>

</body>
</html>